# Generated by Django 4.2.16 on 2024-10-20 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_url', models.URLField(max_length=350)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='StaffHaveSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_url', models.URLField(max_length=350)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.socialmedia')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('staff', 'social_media')},
            },
        ),
    ]
