# Generated by Django 4.2.15 on 2024-11-17 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_socialmedia_created_at_socialmedia_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffhavesocialmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffhavesocialmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
