# Generated by Django 4.2.15 on 2024-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_staffhavesocialmedia_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
