# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_socialmedia_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffhavesocialmedia',
            options={'permissions': [('manage_staff_social_media', 'Manage Staff Soial Media')]},
        ),
    ]
