# Generated by Django 4.2.15 on 2024-11-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_alter_staffhavesocialmedia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffhavesocialmedia',
            options={'permissions': [('manage_staffsocialmedia', 'Manage Staff Soial Media')]},
        ),
    ]
