# Generated by Django 4.2.15 on 2024-11-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0006_alter_staffhavesocialmedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffhavesocialmedia',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersocial', to=settings.AUTH_USER_MODEL),
        ),
    ]
