# Generated by Django 4.2.15 on 2024-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
