# Generated by Django 4.2.15 on 2024-10-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_forms_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
