# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_forms_is_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='image',
            new_name='media',
        ),
    ]
