# Generated by Django 4.2.15 on 2024-11-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_image_forms_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
