# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'permissions': [('manage_forms', 'Manage Forms')]},
        ),
    ]
