# Generated by Django 4.2.15 on 2024-11-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_forms_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('manage_formscategory', 'Manage Forms Category')]},
        ),
    ]
