# Generated by Django 4.2.15 on 2025-08-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={},
        ),
    ]
