# Generated by Django 4.2.15 on 2025-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_category_options_remove_category_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='forms',
            name='position',
        ),
        migrations.AddField(
            model_name='forms',
            name='apply_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
