# Generated by Django 4.2.15 on 2025-09-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_forms_options_remove_forms_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
