# Generated by Django 4.2.15 on 2025-09-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='category',
        ),
        migrations.AddField(
            model_name='forms',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='forms', to='forms.category'),
        ),
    ]
