# Generated by Django 5.1.2 on 2024-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlink',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='project',
            name='case_study',
        ),
        migrations.RemoveField(
            model_name='projectlink',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.ManyToManyField(related_name='project_link', to='projects.projectlink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_service',
            field=models.ManyToManyField(related_name='project_services', to='projects.projectservice'),
        ),
    ]
