# Generated by Django 4.2.16 on 2024-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='url',
            field=models.URLField(default='www', max_length=2000),
            preserve_default=False,
        ),
    ]
