# Generated by Django 4.2.16 on 2024-10-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0001_initial'),
        ('projects', '0002_projectlink_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='casestudy.casestudy'),
            preserve_default=False,
        ),
    ]
