# Generated by Django 5.1.2 on 2024-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
