# Generated by Django 5.1.2 on 2024-10-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0001_initial'),
        ('projects', '0004_project_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_case', to='casestudy.casestudy'),
        ),
    ]
