# Generated by Django 4.2.15 on 2024-10-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_case_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservice',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
