# Generated by Django 4.2.15 on 2024-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectservice_is_feature_projectservice_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
