# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectgroup_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectservice',
            old_name='image',
            new_name='media',
        ),
    ]
