# Generated by Django 4.2.15 on 2024-11-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0010_alter_casestudy_author_alter_casestudy_description_and_more'),
        ('projects', '0008_rename_image_projectservice_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='case_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_case', to='casestudy.casestudy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.ManyToManyField(blank=True, related_name='project_link', to='projects.projectlink'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_service',
            field=models.ManyToManyField(blank=True, related_name='project_services', to='projects.projectservice'),
        ),
    ]
