# Generated by Django 4.2.15 on 2024-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_case_study_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='position',
            field=models.PositiveIntegerField(default=9999, unique=True),
        ),
    ]
