# Generated by Django 4.2.15 on 2024-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectgroup_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
