# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projectgroup_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('manage_project', 'Manage Project')]},
        ),
        migrations.AlterModelOptions(
            name='projectgroup',
            options={'permissions': [('manage_project_group', 'Manage Project Group')]},
        ),
        migrations.AlterModelOptions(
            name='projectservice',
            options={'permissions': [('manage_project_service', 'Manage Project Service')]},
        ),
    ]
