# Generated by Django 4.2.15 on 2025-08-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgroup',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
