# Generated by Django 4.2.15 on 2025-08-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projectgroup_options_projectgroup_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ManyToManyField(null=True, related_name='projects', to='projects.projectgroup'),
        ),
    ]
