# Generated by Django 4.2.15 on 2025-08-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_project_group_project_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='group',
            new_name='cateogry',
        ),
    ]
