# Generated by Django 4.2.15 on 2025-08-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_group_project_cateogry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cateogry',
            new_name='group',
        ),
    ]
