# Generated by Django 4.2.15 on 2024-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='description',
            new_name='testimonial',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
