# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_rename_description_testimonial_testimonial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='image',
            new_name='media',
        ),
    ]
