# Generated by Django 4.2.15 on 2024-11-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_rename_image_testimonial_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'permissions': [('manage_testimonial', 'Manage Testimonial')]},
        ),
    ]
