# Generated by Django 4.2.15 on 2025-08-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0004_alter_testimonial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='media',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(max_length=155),
        ),
    ]
