# Generated by Django 4.2.15 on 2025-09-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0005_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
