# Generated by Django 4.2.15 on 2025-09-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=128)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_user', to='teammember.teammemberinvitation')),
            ],
        ),
    ]
