# Generated by Django 4.2.15 on 2025-09-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0002_pendingteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teammember.teammembercategory'),
        ),
        migrations.AddField(
            model_name='teammemberinvitation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teammember.teammembercategory'),
        ),
    ]
