# Generated by Django 4.2.15 on 2025-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teammember', '0003_teammembercategory_teammember_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberinvitation',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
