# Generated by Django 4.2.15 on 2025-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0004_teammemberinvitation_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberinvitation',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
