# Generated by Django 4.2.15 on 2025-09-17 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teammember', '0006_alter_teammember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammemberinvitation',
            name='position',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammemberinvitation',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member_invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
