# Generated by Django 4.2.15 on 2025-09-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0007_teammember_position_teammemberinvitation_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberinvitation',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
