# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_image_gallery_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': [('manage_gallery', 'Manage Gallery')]},
        ),
    ]
