# Generated by Django 4.2.16 on 2024-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exprience_number', models.PositiveIntegerField()),
                ('success_stories_number', models.PositiveIntegerField()),
                ('team_member_number', models.PositiveIntegerField()),
                ('project_completed_number', models.PositiveIntegerField()),
                ('privacy_policy', models.TextField()),
                ('terms_and_condition', models.TextField()),
            ],
        ),
    ]
