# Generated by Django 4.2.15 on 2024-10-28 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='exprience_number',
            new_name='experience_number',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='terms_and_condition',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
