# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_privacypolicy_termandcondition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'permissions': [('manage_privacy_policy', 'Manage Privacy Policy')]},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'permissions': [('manage_site_settings', 'Manage Site Settings')]},
        ),
        migrations.AlterModelOptions(
            name='termandcondition',
            options={'permissions': [('manage_terms_conditions', 'Manage Terms Conditions')]},
        ),
    ]
