# Generated by Django 4.2.15 on 2024-11-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_alter_privacypolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'permissions': [('manage_privacypolicy', 'Manage Privacy Policy')]},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'permissions': [('manage_sitesettings', 'Manage Site Settings')]},
        ),
        migrations.AlterModelOptions(
            name='termandcondition',
            options={'permissions': [('manage_termsandconditions', 'Manage Terms And Conditions')]},
        ),
    ]
