# Generated by Django 4.2.15 on 2025-09-19 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbranding',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_branding.position'),
        ),
    ]
