# Generated by Django 4.2.15 on 2025-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_branding', '0002_alter_webbranding_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webbranding',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='webbranding',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
