# Generated by Django 4.2.15 on 2024-10-28 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_is_show'),
        ('newslettersubscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='service',
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='category',
            field=models.ManyToManyField(related_name='blogcategory_newsletter', to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
