# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersubscription', '0002_remove_newslettersubscription_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'permissions': [('manage_news_letter_subscription', 'Manage News Letter Subscription')]},
        ),
    ]
