# Generated by Django 4.2.15 on 2024-11-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersubscription', '0003_alter_newslettersubscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'permissions': [('manage_newslettersubscription', 'Manage NewsLetterSubscription')]},
        ),
    ]
