# Generated by Django 4.2.15 on 2025-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('is_static', models.BooleanField(blank=True, default=False)),
                ('static_type', models.CharField(blank=True, choices=[('homepage', 'Homepage'), ('services', 'Services'), ('career', 'Career'), ('about_us', 'About Us')], max_length=10, null=True)),
                ('image', models.FileField(max_length=500, upload_to='gallery/images')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
