# Generated by Django 4.2.15 on 2025-09-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('homepage', 'Homepage'), ('services', 'Services'), ('career', 'Career'), ('about_us', 'About Us')], max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customgallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customgallery',
            name='static_type',
        ),
        migrations.AddField(
            model_name='customgallery',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customgallery.position'),
        ),
    ]
