# Generated by Django 4.2.15 on 2025-09-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customgallery', '0003_customgallerycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgallery',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='CustomGallery', to='customgallery.customgallerycategory'),
        ),
    ]
