# Generated by Django 4.2.15 on 2025-09-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customgallery', '0004_customgallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgallery',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
