# Generated by Django 4.2.15 on 2025-09-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customgallery', '0005_customgallery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgallery',
            name='video_thumbnail',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='gallery/images'),
        ),
    ]
