# Generated by Django 4.2.15 on 2025-09-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customgallery', '0006_customgallery_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customgallery',
            name='is_static',
        ),
        migrations.RemoveField(
            model_name='customgallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customgallery',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customgallery',
            name='video_thumbnail',
        ),
        migrations.DeleteModel(
            name='CustomGalleryCategory',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
