# Generated by Django 4.2.15 on 2025-09-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescategory',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
