# Generated by Django 4.2.16 on 2024-09-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=300)),
                ('project_detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquires', to='plan.plan')),
                ('project_service', models.ManyToManyField(related_name='inquires', to='projects.projectservice')),
            ],
        ),
    ]
