# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquires',
            options={'permissions': [('manage_inquiries', 'Manage Inquiries')]},
        ),
    ]
