# Generated by Django 4.2.15 on 2025-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('inquires', '0002_alter_inquires_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquires',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='inquires',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='inquires',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='inquires',
            name='project_service',
        ),
        migrations.AddField(
            model_name='inquires',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquires',
            name='services',
            field=models.ManyToManyField(related_name='inquires', to='services.services'),
        ),
    ]
