# Generated by Django 4.2.15 on 2025-08-22 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0003_alter_inquires_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquires',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
