# Generated by Django 4.2.15 on 2025-09-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_show',
        ),
    ]
