# Generated by Django 4.2.15 on 2025-09-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
