# Generated by Django 4.2.15 on 2025-09-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_deleted',
        ),
    ]
