# Generated by Django 4.2.15 on 2025-09-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0008_teammemberinvitation_full_name'),
        ('blogs', '0005_remove_blog_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='teammember.teammember'),
            preserve_default=False,
        ),
    ]
