# Generated by Django 4.2.15 on 2025-09-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_blog_user_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=12, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
