# Generated by Django 4.2.15 on 2025-09-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('meta_title', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_author', models.CharField(blank=True, max_length=300, null=True)),
                ('header_code', models.TextField(blank=True, default='', null=True)),
                ('embedded_code', models.TextField(blank=True, default='', null=True)),
                ('blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
