# Generated by Django 4.2.15 on 2025-09-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blogseosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogseosettings',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogSEOSettings', to='blogs.blog'),
        ),
    ]
