# Generated by Django 4.2.16 on 2024-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], max_length=20)),
                ('loop_type', models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Fourth')], max_length=20)),
                ('delay_time', models.TimeField()),
                ('client', models.ManyToManyField(to='clients.clients')),
            ],
        ),
    ]
