# Generated by Django 4.2.15 on 2024-10-25 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='position',
        ),
        migrations.AddField(
            model_name='clients',
            name='section',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], default='first', max_length=20),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='loop_type',
            field=models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse')], max_length=20),
        ),
    ]
