# Generated by Django 4.2.15 on 2024-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_clients_position_clients_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='client',
            field=models.ManyToManyField(related_name='ClientSettings', to='clients.clients'),
        ),
    ]
