# Generated by Django 4.2.15 on 2024-10-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientsettings_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsettings',
            name='client',
        ),
    ]
