# Generated by Django 4.2.15 on 2024-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_clientsettings_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
