# Generated by Django 4.2.15 on 2024-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clients_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='clients'),
        ),
    ]
