# Generated by Django 4.2.15 on 2024-11-11 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_clients_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
