# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clients_public_id_clients_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'permissions': [('manage_clients', 'Manage Clients')]},
        ),
        migrations.AlterModelOptions(
            name='clientsettings',
            options={'permissions': [('manage_client_settings', 'Manage Client Settings')]},
        ),
    ]
