# Generated by Django 4.2.15 on 2024-11-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_clients_options_alter_clientsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsettings',
            options={'permissions': [('manage_clientsettings', 'Manage Client Settings')]},
        ),
    ]
