# Generated by Django 4.2.15 on 2025-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_clientsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
