# Generated by Django 4.2.15 on 2025-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_clients_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='position',
        ),
        migrations.AddField(
            model_name='clients',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
