# Generated by Django 4.2.15 on 2025-09-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clients_options_remove_clients_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='media',
            field=models.CharField(blank=True, null=True),
        ),
    ]
