# Generated by Django 4.2.15 on 2024-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_groupextension_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupextension',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
