# Generated by Django 4.2.15 on 2024-11-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_customgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='auth.group')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
