# Generated by Django 4.2.15 on 2025-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='professional_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
