# Generated by Django 4.2.15 on 2024-10-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='embedded_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='header_code',
            field=models.TextField(default=''),
        ),
    ]
