# Generated by Django 4.2.15 on 2024-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_embedded_code_blog_header_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
