# Generated by Django 4.2.15 on 2024-10-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
