# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_is_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='image',
            new_name='media',
        ),
    ]
