# Generated by Django 4.2.15 on 2024-11-10 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_image_blogcategory_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
