# Generated by Django 4.2.15 on 2024-11-11 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory_created_at_blogcategory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
