# Generated by Django 4.2.15 on 2025-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='answer',
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
