# Generated by Django 4.2.16 on 2024-10-18 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='enable_auto_expiration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='career',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
