# Generated by Django 4.2.15 on 2024-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_career_enable_auto_expiration_career_expiration_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExprienceLevel',
            new_name='ExperienceLevel',
        ),
        migrations.AddField(
            model_name='career',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
