# Generated by Django 4.2.15 on 2024-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_rename_expriencelevel_experiencelevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
