# Generated by Django 4.2.15 on 2024-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_career_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
    ]
