# Generated by Django 4.2.15 on 2024-10-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_career_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
