# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_alter_career_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='image',
            new_name='media',
        ),
    ]
