# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_career_public_id_career_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'permissions': [('manage_career', 'Manage Career')]},
        ),
    ]
