# Generated by Django 4.2.15 on 2025-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_careercategory_alter_career_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='career_category',
            field=models.ManyToManyField(blank=True, to='career.careercategory'),
        ),
    ]
