# Generated by Django 4.2.15 on 2025-08-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_career_career_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='position',
        ),
    ]
