# Generated by Django 4.2.15 on 2025-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0012_remove_career_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
