# Generated by Django 4.2.15 on 2025-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0013_alter_career_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='career'),
        ),
    ]
