# Generated by Django 4.2.15 on 2025-09-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0014_alter_career_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='enable_auto_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
