# Generated by Django 4.2.15 on 2025-09-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_alter_career_enable_auto_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercategory',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
