# Generated by Django 4.2.15 on 2025-09-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0016_careercategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='media',
            field=models.CharField(blank=True, null=True),
        ),
    ]
