# Generated by Django 4.2.16 on 2024-09-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server_address', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=2000)),
                ('port', models.PositiveIntegerField()),
                ('required_authentication', models.BooleanField(default=True)),
                ('security', models.CharField(choices=[('None', 'None'), ('SSL', 'SSL'), ('TSL', 'TSL')], default='None', max_length=200)),
                ('smtp_username', models.CharField(blank=True, max_length=100, null=True)),
                ('verify_smtp_certificate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('from_name', models.CharField(max_length=155)),
                ('cc', models.CharField(max_length=5000)),
                ('bcc', models.CharField(max_length=5000)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('purpose', models.CharField(choices=[('blog', 'Blog'), ('contact_us', 'Contact Us'), ('newsletter_subscription', 'News Letter Subscription')], max_length=50)),
                ('frequency', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=50)),
                ('frequency_per', models.IntegerField()),
                ('number_of_blog_based_on_user', models.IntegerField(default=1)),
                ('number_of_blog', models.IntegerField(default=1)),
                ('excerpt', models.CharField(max_length=2000)),
                ('featured_image', models.ImageField(upload_to='emailtemplate')),
                ('additional_blog', models.ManyToManyField(to='blog.blog')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory')),
            ],
        ),
    ]
