# Generated by Django 4.2.15 on 2024-10-29 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmanagement',
            old_name='number_of_blog_based_on_user',
            new_name='number_of_blog_attachments_based_on_user',
        ),
        migrations.AddField(
            model_name='emailmanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmanagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
