# Generated by Django 4.2.15 on 2024-10-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0002_rename_number_of_blog_based_on_user_emailmanagement_number_of_blog_attachments_based_on_user_and_mor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('subject', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('failed', 'failed'), ('scheduled', 'scheduled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
