# Generated by Django 4.2.15 on 2024-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0003_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('failed', 'failed'), ('scheduled', 'scheduled'), ('canceled', 'canceled')], default='sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
