# Generated by Django 4.2.15 on 2024-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0004_emaillog_preview_emaillog_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='purpose',
            field=models.CharField(choices=[('blog', 'Blog'), ('contact_us', 'Contact Us'), ('newsletter_subscription', 'News Letter Subscription')], max_length=50),
        ),
    ]
