# Generated by Django 4.2.15 on 2024-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0005_alter_emaillog_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanagement',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
