# Generated by Django 4.2.15 on 2024-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0006_emailmanagement_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLogRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=230)),
            ],
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='purpose',
            field=models.CharField(choices=[('contact_us', 'Contact Us'), ('newsletter_subscription', 'News Letter Subscription')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='recipient',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='recipient',
            field=models.ManyToManyField(to='emailmanagement.emaillogrecipient'),
        ),
    ]
