# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0007_emaillogrecipient_alter_emaillog_purpose_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'permissions': [('manage_email_log', 'Manage Email Log')]},
        ),
        migrations.AlterModelOptions(
            name='emailmanagement',
            options={'permissions': [('manage_email_management', 'Manage Email Management')]},
        ),
        migrations.AlterModelOptions(
            name='emailsetup',
            options={'permissions': [('manage_email_setup', 'Manage Email Setup')]},
        ),
    ]
