# Generated by Django 4.2.15 on 2024-11-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanagement', '0008_alter_emaillog_options_alter_emailmanagement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'permissions': [('manage_emaillog', 'Manage Email Log')]},
        ),
    ]
