# Generated by Django 4.2.16 on 2024-09-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_location', models.URLField(max_length=2000)),
                ('company_name', models.CharField(max_length=350)),
                ('company_address', models.CharField(max_length=500)),
                ('email_address', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='globalpresence')),
            ],
        ),
    ]
