# Generated by Django 4.2.15 on 2024-10-28 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globalpresence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpresence',
            name='world_location',
        ),
        migrations.AddField(
            model_name='globalpresence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalpresence',
            name='global_presence',
            field=models.CharField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalpresence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
