# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalpresence', '0002_remove_globalpresence_world_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalpresence',
            old_name='image',
            new_name='media',
        ),
    ]
