# Generated by Django 4.2.15 on 2024-11-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalpresence', '0003_rename_image_globalpresence_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='globalpresence',
            name='global_presence',
        ),
        migrations.AddField(
            model_name='globalpresence',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='global_presences', to='globalpresence.country'),
            preserve_default=False,
        ),
    ]
