# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalpresence', '0004_country_remove_globalpresence_global_presence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpresence',
            options={'permissions': [('manage_global_presence', 'Manage Global Presence')]},
        ),
    ]
