# Generated by Django 4.2.15 on 2024-11-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalpresence', '0005_alter_globalpresence_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpresence',
            name='country',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
