# Generated by Django 4.2.15 on 2024-11-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalpresence', '0006_alter_globalpresence_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpresence',
            options={'permissions': [('manage_globalpresence', 'Manage GlobalPresence')]},
        ),
    ]
