# Generated by Django 4.2.15 on 2024-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_feature_checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
