# Generated by Django 4.2.15 on 2024-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_features_is_feature_checked_plan_is_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(),
        ),
    ]
