# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_plan_is_popular_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'permissions': [('manage_feature', 'Manage Feature')]},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': [('manage_plan', 'Manage Plan')]},
        ),
        migrations.AlterModelOptions(
            name='planhavefeatures',
            options={'permissions': [('manage_plan_have_features', 'Manage Plan Have Features')]},
        ),
    ]
