# Generated by Django 4.2.15 on 2025-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_features_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='planhavefeatures',
            options={},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='position',
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
