# Generated by Django 4.2.16 on 2024-09-13 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudyTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(upload_to='casestudy/')),
                ('excerpt', models.CharField(max_length=300)),
                ('is_publish', models.BooleanField(default=True)),
                ('meta_description', models.CharField(max_length=1200)),
                ('meta_keywords', models.CharField(max_length=800)),
                ('meta_author', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casestudy.casestudycategory')),
                ('tags', models.ManyToManyField(to='casestudy.casestudytags')),
            ],
        ),
    ]
