# Generated by Django 4.2.15 on 2024-10-28 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='is_publish',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='embedded_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='header_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='site_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casestudycategory',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='category',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='case_study'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='casestudycategory',
            name='image',
            field=models.ImageField(null=True, upload_to='case_studycategory'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='category',
            field=models.ManyToManyField(to='casestudy.casestudycategory'),
        ),
    ]
