# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0002_remove_casestudy_is_publish_casestudy_embedded_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudycategory',
            old_name='image',
            new_name='media',
        ),
    ]
