# Generated by Django 4.2.15 on 2024-11-11 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0003_rename_image_casestudycategory_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
