# Generated by Django 4.2.15 on 2024-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0004_casestudy_public_id_casestudy_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
