# Generated by Django 4.2.15 on 2024-11-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0005_casestudy_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='casestudy.casestudycategory'),
        ),
    ]
