# Generated by Django 4.2.15 on 2024-11-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0006_alter_casestudy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='read_time',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
