# Generated by Django 4.2.15 on 2024-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0007_casestudy_read_time_alter_casestudy_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='category',
            field=models.ManyToManyField(blank=True, to='casestudy.casestudycategory'),
        ),
    ]
