# Generated by Django 4.2.15 on 2024-11-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0009_alter_casestudy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='excerpt',
            field=models.CharField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='case_study'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='read_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='tags',
            field=models.ManyToManyField(blank=True, to='casestudy.casestudytags'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(blank=True, max_length=1300, null=True),
        ),
    ]
