# Generated by Django 4.2.15 on 2024-11-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0010_alter_casestudy_author_alter_casestudy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
