# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0011_alter_casestudy_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'permissions': [('manage_case_study', 'Manage Case Study')]},
        ),
    ]
