# Generated by Django 4.2.15 on 2024-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='position',
            field=models.BigIntegerField(default=9999),
        ),
    ]
