# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'permissions': [('manage_contact_us', 'Manage Contact Us')]},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'permissions': [('manage_Faqs', 'Manage Email Faqs')]},
        ),
    ]
