# Generated by Django 4.2.15 on 2025-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_alter_contactus_options_alter_faqs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='faqs',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faqs',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='position',
        ),
        migrations.AddField(
            model_name='faqs',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
