# Generated by Django 4.2.15 on 2025-08-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0006_faqscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='faqs_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faqs.faqscategory'),
        ),
    ]
