# Generated by Django 4.2.15 on 2025-09-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0007_faqs_faqs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqscategory',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
