# Generated by Django 4.2.15 on 2025-09-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0008_faqscategory_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='faqs_category',
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_category',
            field=models.ManyToManyField(blank=True, related_name='faqs', to='faqs.faqscategory'),
        ),
    ]
