# Generated by Django 4.2.15 on 2024-10-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careergallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careergallery',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_galleries', to='careergallery.album'),
        ),
        migrations.AlterField(
            model_name='careergallery',
            name='position',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
