# Generated by Django 4.2.15 on 2024-10-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careergallery', '0002_alter_careergallery_album_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careergallery',
            old_name='image',
            new_name='media',
        ),
    ]
