# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careergallery', '0003_rename_image_careergallery_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careergallery',
            options={'permissions': [('manage_career_gallery', 'Manage Career Gallery')]},
        ),
    ]
