# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_updated_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('manage_notification', 'Manage Notification')]},
        ),
    ]
