# Generated by Django 4.2.15 on 2024-11-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
