# Generated by Django 4.2.15 on 2024-11-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_created_at_department_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('manage_department', 'Manage Department')]},
        ),
    ]
